FROM oryd/kratos:v1.3.1

COPY kratos.yml /etc/kratos/kratos.yml
COPY identity.schema.json /etc/kratos/identity.schema.json
COPY mappers/ /etc/kratos/mappers/
COPY entrypoint.sh /etc/kratos/entrypoint.sh
